### PR TITLE
Translated newly added strings into Czech

### PR DESCRIPTION
**Pull request by p-bo**

### CODE REVIEW

**Comment by JonMagon** [comment]
Hi! There's nothing updated, translation for new messages is still unfinished. For example, https://github.com/p-bo/KDiskMark/blob/81fcbf5e7f829970d47c6d04d9b3ada1287017ee/data/translations/kdiskmark_cs_CZ.ts#L90

**Review by p-bo — COMMENTED** [review]
Fixed omission of strings with tag unfinished.

**Comment by JonMagon** [comment]
Great, thank you!

**Comment by p-bo** [comment]
> Hi! There's nothing updated, translation for new messages is still unfinished. For example, https://github.com/p-bo/KDiskMark/blob/81fcbf5e7f829970d47c6d04d9b3ada1287017ee/data/translations/kdiskmark_cs_CZ.ts#L90


> Great, thank you!

Glad to help!
(and sorry for messing it up at first -  overlooked it due wrong search string (searched for empty strings between translation tags instead of tag unfinished) )

**Comment by JonMagon** [comment]
It's ok. 🙂

**Pull request merged**
